### ISSUE TITLE
Feature Request: Blinking Led

### ISSUE THREAD

**Issue by ABadoil** [jean-emmanuel/open-stage-control#150]
Hello,
Would it be possible to have a blinking option for the LED widget when it's value is at 1?
Thanks!

**Comment by cyberic99** [comment]
@jean-emmanuel I thought about it too, and was wondering if it could be done by css
Sometime you also need to flash a widget for say 5s, then stop.
I think custom css could help, and we would only need a class to be added to the widget when set to 1

**Comment by jean-emmanuel** [comment]
The `css`  property did not support animations until now (in git, -> next release). Attached session file shows an example where the led's css animation is enabled only when the fader's value is `1` by using the to-be-released property maths syntax.

**Comment by jean-emmanuel** [comment]
[led-blink.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1716463/led-blink.json.txt)

**Comment by cyberic99** [comment]
From what I understand, you can put MathJS instead the css expression? That's cool!

**Comment by cyberic99** [comment]
What would be the corret way to do the same with a compact fader? I haven't found the correct css class to alter...
thanks

**Comment by jean-emmanuel** [comment]
Targetting the `canvas` element should do it :

```css

@keyframes blink {
   0% {opacity:1;}
   50% {opacity:0.5;}
}
canvas {
   animation: blink .1s steps(1) #{@{fader_1} == 1 ? "infinite": 0}
}

```


Le 13/02/2018 à 15:43, cyberic99 a écrit :

**Comment by cyberic99** [comment]
It works great, thanks.
And last question, it it possible to refer to the widget's own value, instead of another widget value?
Thanks again
PS: all these tips should really be in an example file or in a 'recipies' pages, don't you think?

**Comment by jean-emmanuel** [comment]
> And last question, it it possible to refer to the widget's own value, 
instead of another widget value?


Yes but only to define dynamic values, otherwise the value will be 
undefined. Dynamic values will all be marked in the docs and they are 
now marked in the editor as well.


 > PS: all these tips should really be in an example file or in a 
'recipies' pages, don't you think?


Yes, some sort of FAQ section would be nice indeed.

**Comment by cyberic99** [comment]
oh I didn't notice it in the editor. will have a look.
so if I want to make a fader blink when its value is below a certain threshold, how can I do?
I tried to use a condition ``#{fader_id}>0.5``, but it does not seem to work.

About the FAQ:
IMO, for each 'tip', some short examples with screenshots would be better than a whole session file

**Comment by jean-emmanuel** [comment]
`#{}` must contain the formula : `#{fader_id}` will just try to evaluate a variable named "fader_id".
```css
@keyframes blink {
   0% {opacity:1;}
   50% {opacity:0.5;}
}
canvas {
   animation: blink .1s steps(1) #{@{fader_1} >= 0.5 ? "infinite": 0}
}
```
