### ISSUE TITLE
v0: css tricks 

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#152]
**Blinking LED**

*How to make a led blink depending on its value*

**`css:`**

```css
/* Do the maths here to keep css as clean as possible */
/* Assigned variables are available to the formulas that come after */
#{
    threshold = 0.5;
    value = @{this};
    animationCount = value >= threshold ? "infinite": "0";
}

/* animation names are not scoped to the widget only and can be used in other widgets */
@keyframes blink {
    0% {opacity:1;}
    50% {opacity:0.5;}
}

/* To get the element's classname, open the dev panel (F12) and look for it ;) 
/* We use a formula to define whether the animation should run or not */
.led {
    animation: blink .1s steps(1) #{animationCount};
}
```

This snippet applies to led widgets. You can use it on a toggle with `led` set to `true` by replacing the css selector `.led` with `.toggle:after`.

**Comment by jean-emmanuel** [comment]
**Untouchable fader**

**`css:`**

```css

.fader {
    pointer-events:none;
}

```

**Comment by cyberic99** [comment]
*How to format a number in seconds (pos) to padded mm:ss*
In value, put:
```
#{m=floor(@{pos}/60);pm=(m<=9)?"0":"";pm}#{m}:#{s=floor(@{pos}%60.0);ps=(s<=9)?"0":"";ps}#{s}
```

**Comment by cyberic99** [comment]
Here is a qick example of SVG support...
For now, this example is not very useful...

**Comment by cyberic99** [comment]
Here is an example of a pyhon OSC client and server.
It uses /EDIT to get an object, clone it, then reinject it in the tab

```python
#!/usr/bin/env python3
# coding=utf-8

from pythonosc import osc_message_builder
from pythonosc import udp_client
from pythonosc import dispatcher
from pythonosc import osc_server

import queue
import time
import threading
import json

"""
This program will:
- instantiate an OSC listening server
- send an /EDIT/GET on object WID_PARENT
- if this WID_PARENT has a child widget named WID_TO_CLONE,
  - delete any cloned instance of WID_TO_CLONE (if DEL_EXISTING_CLONES is true)
  - create NB_CLONES clones of the WID_TO_CLONE widget

Lots of things are a bit hacky...
But it should only be used as an example
"""

# OSC listening address and port
ip = "127.0.0.1"
port = 6666

WID_TO_CLONE = "strip_1"
WID_PARENT = "tab_1"
DEL_EXISTING_CLONES = True
NB_CLONES = 5


def recv_osc(*args):
    if args[0] == "/EDIT/GET" and args[1] == WID_PARENT:
        j = json.loads(args[2])  # the actual json representation of the widget
        props = {}
        for w in list(j["widgets"]):
            if w["id"] == WID_TO_CLONE:
                props = w["props"]
            if DEL_EXISTING_CLONES:
                if w["type"] == "clone" and w["widgetId"] == WID_TO_CLONE:
                    j["widgets"].remove(w)

        new_w = {'type': 'clone', 'left': 'auto', 'top': 'auto', 'widgetId': WID_TO_CLONE}

        for i in range(0, NB_CLONES):
            new_w["props"] = dict(props)
            if "variables" not in new_w["props"]:
                new_w["props"]["variables"] = {}
            new_w["props"]["variables"]["n"] = i+1
            j["widgets"].append(dict(new_w))

        q.put(j)


if __name__ == '__main__':
    disp = dispatcher.Dispatcher()
    disp.set_default_handler(recv_osc)

    q = queue.Queue()
    server = osc_server.OSCUDPServer((ip, port), disp)
    server_thread = threading.Thread(target=server.serve_forever)
    server_thread.setDaemon(True)
    server_thread.start()

    client = udp_client.SimpleUDPClient(ip, 8080)

    msg = osc_message_builder.OscMessageBuilder(address="/EDIT/GET")
    msg.add_arg("{}:{}".format(ip, port))
    msg.add_arg(WID_PARENT)
    client.send(msg.build())
    time.sleep(0.5)  # should not be needed, since the queue.read() is blocking

    jj = q.get()
    jj = {"widgets": jj["widgets"]}

    msg = osc_message_builder.OscMessageBuilder(address="/EDIT")
    msg.add_arg(WID_PARENT)
    msg.add_arg(json.dumps(jj))

    client.send(msg.build())
    time.sleep(0.5)

```

**Comment by jean-emmanuel** [comment]
**Hold a widget's value**

*How to save another widget's value when pressing a button. For instance, let's save a fader's value (and hold it) to an input widget when pressing a push button.*

**`value`:**
```
#{
# if the push is pressed, the input takes the fader's value
# otherwise it takes its own value (ie nothing changes)
@{push_1} ? @{fader_1} : @{this}
}
```

**Comment by jean-emmanuel** [comment]
**Lock orientation in landscape mode (iOS)**

https://www.reddit.com/r/iphone/comments/4lcwej/there_is_a_way_to_lock_landscape_mode/?st=je41ol0d&sh=3bbfdd79

**Comment by Sebastian-blu** [comment]
I was seeing if I could run this setup with the laptop and tablet on a adhoc network off the Mac but it needs internet to open on the tablet side. I tried teathering them both to my cell internet. That didn’t work either thought they both have internet signal at that point. Hoping to bring my new interface to rehearsal tonight to dial in headphone mixes etc. Advice?

**Comment by cyberic99** [comment]
I have used simpleRT to get reverse tethering between a Linux PX and an Android tablet.

Would it work for you?

https://github.com/vvviperrr/SimpleRT

**Comment by Sebastian-blu** [comment]
not sure, it looks android specific not iOS

**Comment by Sebastian-blu** [comment]
also Im hoping to run this without internet like at show and rehearsal space if possible

**Comment by jean-emmanuel** [comment]
**Pulse Led**

*How to make a led pulse when receiving a message on a specific address*

`css`:
```
#{
    OSC{/pulse}; # subscribe to osc messages on address "/pulse"
    T = timestamp(); # generate timestamped css animations to force reset 
}

@keyframes pulse-#{T} {
    0% {opacity:0;}
    10% {opacity:1;}
    100% {opacity:0;}
}
.led:before {
    animation: pulse-#{T} .5s 1 forwards
}
```

**Comment by guitmart** [comment]
Comment utiliser le widget script, je pense que sais la solution à mon problème, mais je n'arrive pas à le faire fonctionner. Est-ce qu'il y a un petit exemple?

**Comment by jean-emmanuel** [comment]
**Extend nested strip/container's `variables`**

`variables`:
```
#{
new_var = OSC{/new_var};
extend(@{parent.variables}, {"new_var": new_var})
}
```

**Comment by WillyKaze** [comment]
#### Store a value in a strip/container and parse it in children
Useful when a value is a bitmask

strip/container `variables`:
```js
#{
bitmask_value = OSC{/some/path};
extend(@{parent.variables}, {"bitmask_value": bitmask_value})
}
```
In the children `value`:
```js
#{
value = @{parent.variables.bitmask_value};
value = bitAnd(value, 1);
value ? 1 : 0
}
```

**Comment by jean-emmanuel** [comment]
Thanks for your contribution :). Note that you can also use the native bitwise operators (`&` in this case, see https://mathjs.org/docs/reference/functions.html#bitwise-functions).

**Comment by jean-emmanuel** [comment]
**Grid switch**

```css
.switch {
  display:grid;
  /* replace "3" with the number of columns */
  grid-template-columns: repeat(3, 1fr);
  grid-gap: 1rem;
}
.value {
  margin:0;
  border:0;
}
```
