### ISSUE TITLE
how do I set the tex box background to transparent

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#227]
I would like to se the text box background to transparent but leave the text visible

something like this I found on w3 schools css

///    background: rgba(76, 175, 80, 0.3)

**Comment by jean-emmanuel** [comment]
This makes the text widget transparent and removes its borders. 
```css
&, .text, .text:after {
background:transparent;
border-color:transparent;
box-shadow:none;
}
```
