### ISSUE TITLE
Dropdown without the empty value

### ISSUE THREAD

**Issue by suhr** [jean-emmanuel/open-stage-control#317]

**Comment by jean-emmanuel** [comment]
You can hide the empty value by adding this to the widget's css option:
```css
option:first-child {
  display:none;
}
```
