### ISSUE TITLE
Hide sidebar

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#363]
Is there anyway to disable the side bar where it can not be accessed

**Comment by jean-emmanuel** [comment]
You could write a custom css theme to hide it:
```css
/* no-sidepanel.css */
#open-toggle, #sidepanel {
  display:none;
}
``` 
http://osc.ammd.net/extras/theming/

There's also the `--read-only` option that disables the editor if that's what you're after.

http://osc.ammd.net/getting-started/
