### ISSUE TITLE
Image as background: multixy/xy feature request(s)

### ISSUE THREAD

**Issue by akobelan** [jean-emmanuel/open-stage-control#415]
Great work jean-emmanuel.

How would I go about specifying an image as a background for the multixy/xy widgets? When I specify
a background-image in the css box, only the label bar and what looks like the widget border get filled in.

I'd like to be able to put an image of a football field, soccer pitch, or hockey rink, for example and specify 
points corresponding to the athletes.  I can send labels to the points to distinguish them (with initials, for example). I'm almost there. 

Also, if it were possible to select a colour for each point (and ideally an opacity), some very interesting user interfaces could be constructed.

**Comment by akobelan** [comment]
If I were able to lower the opacity of the multixy/xy canvas but maintain the opacity of the points, I would be satisfied with overlaying the multixy/xy widget over an image widget.

**Comment by jean-emmanuel** [comment]
While implementing #416, I've done some design improvements on pads. The second example above no longer works and can be done in a more simple way:
```css
--background: color-or-url;
```
Under the hood, it affects this element:
```css
> .pad > .wrapper:after {
background: var(--background);
}
```

**Comment by akobelan** [comment]
I can confirm that the following works on **0.39.3** for an 8 point *multixy* with a specified url for the image being displayed. 

Refrence for CSS background property:
https://www.w3schools.com/cssref/css3_pr_background.asp

CSS used in Style->CSS:

```css
.pad-0 {
  --color-custom: yellow;
}
.pad-1 {
  --color-custom: red; 
}
> .pad > .wrapper:after {
background: url('https://faulknerbrowns.co.uk/media/stories/velodrome-design-expertise-track-geometry-diagram-l.png') no-repeat;
background-size:contain;
background-position:center;
object-width=scale-down;
}
```
If you try this example, it will place the image referenced by the URL in the middle of the multixy widget with one pad coloured yellow, one pad colored red, and the rest the default color (blue in my case). 

[This](https://postimg.cc/fVGP0CGq) is what it looks like. Very nice result. The points themselves can be updated and appear to stay on the track with a suitable mathematical representation of the track. 

Thanks, @jean-emmanuel,  for pointing me in the right direction.
