### ISSUE TITLE
Multiple Color Condition

### ISSUE THREAD

**Issue by dtsmarin** [jean-emmanuel/open-stage-control#461]
What is the correct syntax for this situation:
I have a parameter that sends a value to a button. I need the button to change its color depending on that value.
If I add two conditions it works fine. As soon as I add a third one it doesn't work.

:host {
border:none;
text-transform:none;
border-radius:3px;
line-height:160%;

#{ 
    @{color} == 1 ?   "background:#00CED1;color: #F0FFFF;" : "background:#00CED1;color:#F0FFFF; "background:#8B0000;color: #F0FFFF;""  }

 #{
    @{color} == 2 ?   "background:#2F4F4F;color: #F0FFFF;" : "background:#00CED1;color:#F0FFFF;" } 
 #{
    @{color} == 3 ?   "background:#8B0000;color: #F0FFFF;" : "background:#2F4F4F;color:#F0FFFF;" } 
 }

**Comment by jean-emmanuel** [comment]
Hi, here is a more clean way of writing this:
```css
:host {
border:none;
text-transform:none;
border-radius:3px;
line-height:160%;
#{

# set fallback color 
color =  "background:#00CED1;color:#F0FFFF;" ;

# set conditional color
@{color} == 1 ? color = "background:#00CED1;color: #F0FFFF;" : "";
@{color} == 2 ? color = "background:#2F4F4F;color: #F0FFFF;" : "";
@{color} == 3 ? color = "background:#8B0000;color: #F0FFFF;" : "";

# output color variable (no semi-colon)
color

}
```
