### ISSUE TITLE
Is it possible to change the color of a toggle globally instead of just having a small LED lit?

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#476]
I suppose it's possible with some css? I have no clue how to do it

**Comment by jean-emmanuel** [comment]
If disabling the `led` option is not enough, you can enable the built-in theme `alt-buttons` which increases buttons' contrast. Alternatively you can copy the part that affects toggles and put it in the root's `css` : 

```css
.widget.toggle-container.on:not(.led) {
	background : var(--color-custom);
	color: var(--color-bg);
	font-weight: 900;
}
```
From https://github.com/jean-emmanuel/open-stage-control/blob/master/src/scss/themes/alt-buttons.scss
