### ISSUE TITLE
[Feature] Strip container > "from bottom" option

### ISSUE THREAD

**Issue by Manaberry** [jean-emmanuel/open-stage-control#523]
Hi,

I see there is no way to list items in a strip container starting from the bottom instead of the top without using stretch feature.
Is it easy to do this?

**Comment by jean-emmanuel** [comment]
The following css will do the trick:
```css
.panel {
flex-direction: column-reverse;
}
```
