### ISSUE TITLE
[Feature] Reduce minimum width of Root tab

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#698]
Hello,

I would like to be able to reduce the width of the Root tab more than it is possible currently because I am working with a screen in portrait mode.

Thank you for considering my request.

Best regards.

**Comment by jean-emmanuel** [comment]
did you try setting the root widget's width property ?

Le 28/03/2021 à 09:25, nesdnuma a écrit :

**Comment by nesdnuma** [comment]
I have just figured out I did not make myself clear: this is not the  width of the Root widget I want to reduce, but the width of the Arborescence tab without closing it totally.

**Comment by jean-emmanuel** [comment]
You can do that with a theme file:
```css
osc-panel-container.left:not(.minimized) {
  min-width: 150rem!important;
}
```
