### ISSUE TITLE
[Bug] custom CSS file using ":root" no longer works after v1.17.1-beta2

### ISSUE THREAD

**Issue by DMDComposer** [jean-emmanuel/open-stage-control#794]
I just reverted back tov1.17.1-beta2 to test, and my custom CSS theme files function as normal. 
Some simple CSS works in v1.17.1-beta2 but breaks in any version after. Any global var used in :root isn't read.
```css
:root {
  /* --bg-color-default: #314559; */
  --bg-color-default: #1e1e1e;
  --bg-repeat: no-repeat;
  --bg-position: center 45%;
  --bg-size: 40%;
  --border-radius: 5rem;
}
.Button_1 {
  text-transform: none;
  border: none;
  border-radius: var(--border-radius);
  background-color: var(--bg-color-default);
  display: grid;
  place-items: center;
}
```

Cheers,
DMDComposer
